//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookYourFav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int mid { get; set; }
        public string mname { get; set; }
        public string mtheaterName { get; set; }
        public string mlocation { get; set; }
        public Nullable<int> mticketAllocated { get; set; }
        public Nullable<int> mticketBooked { get; set; }
    }
}
